In [ ]:
import numpy as np
from numpy import random
randomValArr = random.normal(size=(1, 3))
print(randomValArr)

[[-0.67759257 -1.48351115  1.27348312]]


In [ ]:
from numpy import random
x = random.binomial(n=10, p=0.5, size=10) #n and p are parameters of binomial
print(x)

[7 1 6 8 4 5 5 4 6 3]


In [ ]:
from numpy import random
x = random.poisson(lam=5, size=9)
print(x)

[6 3 4 2 4 4 3 2 4]


In [ ]:
from numpy import random
x = random.uniform(size=(3, 3))
print(x)

[[0.84422699 0.74399289 0.38436308]
 [0.28252836 0.51662481 0.13664263]
 [0.24884298 0.69845552 0.12571134]]


In [ ]:
from numpy import random
distribution = random.logistic(loc=1, scale=2, size=(2, 3))
print(distribution)

[[ 3.60322458  2.12264551  1.12963385]
 [ 9.80307004 -0.48242581 -1.29238019]]


In [ ]:
import numpy as np
def UnivSubtract(x, y):
  return x-y
myadd = np.frompyfunc(UnivSubtract, 2, 1)
print(myadd([40, 45, 7, 9], [5, 6, 7, 8]))

[35 39 0 1]


In [ ]:
import numpy as np

arr1 = np.array([10,20,30,40,50,60])
arr2 = np.array([3,5,10,8,2,33])

newarr = np.divide(arr1,arr2)

print(newarr)

[ 3.33333333  4.          3.          5.         25.          1.81818182]


In [ ]:
import numpy as np
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2= np.array([20, 21, 22, 23, 24, 25])
newarr = np.add(arr1, arr2)
print(newarr)

[30 32 34 36 38 40]


In [ ]:
import numpy as np
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2= np.array([20, 21, 22, 23, 24, 25])
newarr = np.divmod(arr2, arr1)
print(newarr)

(array([2, 1, 1, 1, 1, 1]), array([ 0, 10, 10, 10, 10, 10]))


In [ ]:
import numpy as np

arr = np.around(3.1666,2)

print(arr)

3.17


In [ ]:
import numpy as np
arr1 = np.array([10, 11, 12, 13, 14, 15])
arr2= np.array([20, 21, 22, 23, 24, 25])

newarr = np.add(arr1,arr2)
newarr2 = np.sum([arr1,arr2])
arr3 = np.sum([arr1,arr2],axis=1)
print(newarr)
print(newarr2)
print(arr3)

[30 32 34 36 38 40]
210
[ 75 135]


In [ ]:
import numpy as np
arr = np.arange(1,10)

print(np.log2(arr))

[0.         1.         1.5849625  2.         2.32192809 2.5849625
 2.80735492 3.         3.169925  ]


In [7]:
import numpy as np

arr = np.array([3,6,9])

x = np.lcm.reduce(arr)

print("Pie value:",np.pi)
y = np.sinh(np.pi/2)
print(y)
print("LCM: ")
print(x)


Pie value: 3.141592653589793
2.3012989023072947
LCM: 
18


In [10]:
import numpy as np
arrToSet = np.array([1,1,1,2,3,4,4,6,7])
print("Array to a set: ",np.unique(arrToSet))

set1 = np.array([1,2,3,4])
set2 = np.array([3,4,5,6])

ARR = np.setdiff1d(set1, set2,assume_unique=True)
print(ARR)

Array to a set:  [1 2 3 4 6 7]
[1 2]
